-- Initial data for organizations table
-- Generated from docs/ORGANIZATIONS.csv

INSERT INTO organizations (code, name) VALUES ('﻿1140100', '국민권익위원회');
INSERT INTO organizations (code, name) VALUES ('6410000', '경기도');
INSERT INTO organizations (code, name) VALUES ('B552522', '한국서부발전(주)');
INSERT INTO organizations (code, name) VALUES ('6500000', '제주특별자치도');
INSERT INTO organizations (code, name) VALUES ('1192000', '해양수산부');
INSERT INTO organizations (code, name) VALUES ('6260000', '부산광역시');
INSERT INTO organizations (code, name) VALUES ('1290000', '국방부');
INSERT INTO organizations (code, name) VALUES ('4641000', '전북특별자치도 전주시');
INSERT INTO organizations (code, name) VALUES ('3120000', '서울특별시 서대문구');
INSERT INTO organizations (code, name) VALUES ('5370000', '경상남도 거제시');
INSERT INTO organizations (code, name) VALUES ('1371029', '문화체육관광부 국립중앙도서관');
INSERT INTO organizations (code, name) VALUES ('1371000', '문화체육관광부');
INSERT INTO organizations (code, name) VALUES ('4590000', '충청남도 청양군');
INSERT INTO organizations (code, name) VALUES ('1543000', '농림축산식품부');
INSERT INTO organizations (code, name) VALUES ('B551004', '영화진흥위원회');
INSERT INTO organizations (code, name) VALUES ('B551282', '강북구도시관리공단');
INSERT INTO organizations (code, name) VALUES ('B550021', '금융감독원');
INSERT INTO organizations (code, name) VALUES ('B554287', '한국사회보장정보원');
INSERT INTO organizations (code, name) VALUES ('B552024', '한국체육산업개발주식회사');
INSERT INTO organizations (code, name) VALUES ('B551182', '건강보험심사평가원');
INSERT INTO organizations (code, name) VALUES ('1790387', '질병관리청');
INSERT INTO organizations (code, name) VALUES ('B553023', '한국원자력환경공단');
INSERT INTO organizations (code, name) VALUES ('1450000', '산업통상자원부');
INSERT INTO organizations (code, name) VALUES ('1833100', '국가유산청');
INSERT INTO organizations (code, name) VALUES ('B554695', '대전교통공사');
INSERT INTO organizations (code, name) VALUES ('1051000', '기획재정부');
INSERT INTO organizations (code, name) VALUES ('1613000', '국토교통부');
INSERT INTO organizations (code, name) VALUES ('B090032', '한국과학기술연구원');
INSERT INTO organizations (code, name) VALUES ('B090028', '한국농촌경제연구원');
INSERT INTO organizations (code, name) VALUES ('B190017', '예금보험공사');
INSERT INTO organizations (code, name) VALUES ('B490007', '한국산업인력공단');
INSERT INTO organizations (code, name) VALUES ('1383000', '여성가족부');
INSERT INTO organizations (code, name) VALUES ('B551904', '한국고용정보원');
INSERT INTO organizations (code, name) VALUES ('1830000', '국가보훈부');
INSERT INTO organizations (code, name) VALUES ('1400000', '산림청');
INSERT INTO organizations (code, name) VALUES ('B552587', '부산시설공단');
INSERT INTO organizations (code, name) VALUES ('B550373', '한국지역난방공사');
INSERT INTO organizations (code, name) VALUES ('3280000', '부산광역시 영도구');
INSERT INTO organizations (code, name) VALUES ('B554390', '국토안전관리원');
INSERT INTO organizations (code, name) VALUES ('B553457', '한국문화정보원');
INSERT INTO organizations (code, name) VALUES ('B550629', '한국교육학술정보원');
INSERT INTO organizations (code, name) VALUES ('1170000', '법제처');
INSERT INTO organizations (code, name) VALUES ('B190031', '한국수출입은행');
INSERT INTO organizations (code, name) VALUES ('5070000', '경상북도 안동시');
INSERT INTO organizations (code, name) VALUES ('1300000', '병무청');
INSERT INTO organizations (code, name) VALUES ('5390000', '경상남도 의령군');
INSERT INTO organizations (code, name) VALUES ('4820000', '전라남도 순천시');
INSERT INTO organizations (code, name) VALUES ('1371480', '문화체육관광부 대한민국역사박물관');
INSERT INTO organizations (code, name) VALUES ('1371034', '문화체육관광부 국립국악원');
INSERT INTO organizations (code, name) VALUES ('1390804', '농촌진흥청 국립원예특작과학원');
INSERT INTO organizations (code, name) VALUES ('1390000', '농촌진흥청');
INSERT INTO organizations (code, name) VALUES ('4440000', '충청북도 영동군');
INSERT INTO organizations (code, name) VALUES ('1661000', '소방청');
INSERT INTO organizations (code, name) VALUES ('4500000', '충청남도 공주시');
INSERT INTO organizations (code, name) VALUES ('B552519', '대전도시공사');
INSERT INTO organizations (code, name) VALUES ('1371028', '문화체육관광부 국립국어원');
INSERT INTO organizations (code, name) VALUES ('6310000', '울산광역시');
INSERT INTO organizations (code, name) VALUES ('B551542', '부산교통공사');
INSERT INTO organizations (code, name) VALUES ('6270000', '대구광역시');
INSERT INTO organizations (code, name) VALUES ('1543061', '농림축산식품부 농림축산검역본부');
INSERT INTO organizations (code, name) VALUES ('3200000', '서울특별시 관악구');
INSERT INTO organizations (code, name) VALUES ('B551959', '한국항공우주연구원');
INSERT INTO organizations (code, name) VALUES ('B552111', '한국과학창의재단');
INSERT INTO organizations (code, name) VALUES ('1320000', '경찰청');
INSERT INTO organizations (code, name) VALUES ('B551178', '한국공항공사');
INSERT INTO organizations (code, name) VALUES ('B552467', '대구경북과학기술원');
INSERT INTO organizations (code, name) VALUES ('B552540', '한국연구재단');
INSERT INTO organizations (code, name) VALUES ('B552015', '국민연금공단');
INSERT INTO organizations (code, name) VALUES ('B551971', '전북개발공사');
INSERT INTO organizations (code, name) VALUES ('6440000', '충청남도');
INSERT INTO organizations (code, name) VALUES ('B555073', '광주교통공사');
INSERT INTO organizations (code, name) VALUES ('B552132', '한국문학번역원');
INSERT INTO organizations (code, name) VALUES ('B552584', '한국환경공단');
INSERT INTO organizations (code, name) VALUES ('1480000', '환경부');
INSERT INTO organizations (code, name) VALUES ('6280000', '인천광역시');
INSERT INTO organizations (code, name) VALUES ('B460014', '한국사회복지협의회');
INSERT INTO organizations (code, name) VALUES ('1721301', '과학기술정보통신부 우정사업본부');
INSERT INTO organizations (code, name) VALUES ('B551919', '한국소비자원');
INSERT INTO organizations (code, name) VALUES ('1741000', '행정안전부');
INSERT INTO organizations (code, name) VALUES ('1721000', '과학기술정보통신부');
INSERT INTO organizations (code, name) VALUES ('1480964', '환경부 한강홍수통제소');
INSERT INTO organizations (code, name) VALUES ('B260003', '한국국제협력단');
INSERT INTO organizations (code, name) VALUES ('9735000', '국회 국회입법조사처');
INSERT INTO organizations (code, name) VALUES ('9710000', '국회 국회사무처');
INSERT INTO organizations (code, name) VALUES ('1371027', '문화체육관광부 국립중앙박물관');
INSERT INTO organizations (code, name) VALUES ('B551010', '한국영상자료원');
INSERT INTO organizations (code, name) VALUES ('B551940', '한국문화관광연구원');
INSERT INTO organizations (code, name) VALUES ('1192136', '해양수산부 국립해양조사원');
INSERT INTO organizations (code, name) VALUES ('6300000', '대전광역시');
INSERT INTO organizations (code, name) VALUES ('1721137', '과학기술정보통신부 국립전파연구원');
INSERT INTO organizations (code, name) VALUES ('B552916', '한국출판문화산업진흥원');
INSERT INTO organizations (code, name) VALUES ('1192073', '해양수산부 국립수산물품질관리원');
INSERT INTO organizations (code, name) VALUES ('B410005', '한국석유공사');
INSERT INTO organizations (code, name) VALUES ('1371037', '문화체육관광부 한국정책방송원');
INSERT INTO organizations (code, name) VALUES ('4040000', '경기도 하남시');
INSERT INTO organizations (code, name) VALUES ('B551015', '한국마사회');
INSERT INTO organizations (code, name) VALUES ('B553734', '서울에너지공사');
INSERT INTO organizations (code, name) VALUES ('B552468', '한국산업안전보건공단');
INSERT INTO organizations (code, name) VALUES ('1270000', '법무부');
INSERT INTO organizations (code, name) VALUES ('B552583', '한국장애인고용공단');
INSERT INTO organizations (code, name) VALUES ('B190001', '한국조폐공사');
INSERT INTO organizations (code, name) VALUES ('5080000', '경상북도 구미시');
INSERT INTO organizations (code, name) VALUES ('B552831', '인천도시공사');
INSERT INTO organizations (code, name) VALUES ('B552041', '한국수력원자력(주)');
INSERT INTO organizations (code, name) VALUES ('B554620', '한국수목원정원관리원');
INSERT INTO organizations (code, name) VALUES ('B552525', '(주)강원랜드');
INSERT INTO organizations (code, name) VALUES ('B551177', '인천국제공항공사');
INSERT INTO organizations (code, name) VALUES ('B410002', '한국전력공사');
INSERT INTO organizations (code, name) VALUES ('4351000', '강원특별자치도 양양군');
INSERT INTO organizations (code, name) VALUES ('3000000', '서울특별시 종로구');
INSERT INTO organizations (code, name) VALUES ('1390906', '농촌진흥청 국립축산과학원');
INSERT INTO organizations (code, name) VALUES ('B410001', '대한무역투자진흥공사');
INSERT INTO organizations (code, name) VALUES ('B551398', '한국전기안전공사');
INSERT INTO organizations (code, name) VALUES ('6110000', '서울특별시');
INSERT INTO organizations (code, name) VALUES ('B551011', '한국관광공사');
INSERT INTO organizations (code, name) VALUES ('6540000', '전북특별자치도');
INSERT INTO organizations (code, name) VALUES ('B552826', '한국임업진흥원');
INSERT INTO organizations (code, name) VALUES ('1471000', '식품의약품안전처');
INSERT INTO organizations (code, name) VALUES ('B552532', '한국석유관리원');
INSERT INTO organizations (code, name) VALUES ('B551963', '한국전자통신연구원');
INSERT INTO organizations (code, name) VALUES ('1352000', '보건복지부');
INSERT INTO organizations (code, name) VALUES ('B551391', '제주국제자유도시개발센터');
INSERT INTO organizations (code, name) VALUES ('1390802', '농촌진흥청 국립농업과학원');
INSERT INTO organizations (code, name) VALUES ('B490001', '근로복지공단');
INSERT INTO organizations (code, name) VALUES ('1430000', '특허청');
INSERT INTO organizations (code, name) VALUES ('B552070', '한국동서발전(주)');
INSERT INTO organizations (code, name) VALUES ('B554035', '한국해양교통안전공단');
INSERT INTO organizations (code, name) VALUES ('B552696', '한국무역보험공사');
INSERT INTO organizations (code, name) VALUES ('1130000', '공정거래위원회');
INSERT INTO organizations (code, name) VALUES ('B552115', '한국전력거래소');
INSERT INTO organizations (code, name) VALUES ('B553766', '서울교통공사');
INSERT INTO organizations (code, name) VALUES ('3740000', '경기도 수원시');
INSERT INTO organizations (code, name) VALUES ('B551014', '서울올림픽기념국민체육진흥공단');
INSERT INTO organizations (code, name) VALUES ('1390803', '농촌진흥청 국립식량과학원');
INSERT INTO organizations (code, name) VALUES ('B553511', '주택도시보증공사');
INSERT INTO organizations (code, name) VALUES ('6470000', '경상북도');
INSERT INTO organizations (code, name) VALUES ('1400119', '산림청 국립수목원');
INSERT INTO organizations (code, name) VALUES ('5410000', '경상남도 창녕군');
INSERT INTO organizations (code, name) VALUES ('6460000', '전라남도');
INSERT INTO organizations (code, name) VALUES ('AAAAAAA', '공공데이터활용지원센터');
INSERT INTO organizations (code, name) VALUES ('1834100', '우주항공청');
INSERT INTO organizations (code, name) VALUES ('1480523', '환경부 국립환경과학원');
INSERT INTO organizations (code, name) VALUES ('B551982', '한국지역정보개발원');
INSERT INTO organizations (code, name) VALUES ('B500001', '한국수자원공사');
INSERT INTO organizations (code, name) VALUES ('1833118', '국가유산청 국립문화유산연구원');
INSERT INTO organizations (code, name) VALUES ('B551008', '영상물등급위원회');
INSERT INTO organizations (code, name) VALUES ('B552895', '농림수산식품교육문화정보원');
INSERT INTO organizations (code, name) VALUES ('3460000', '대구광역시 수성구');
INSERT INTO organizations (code, name) VALUES ('1543145', '농림축산식품부 국립농산물품질관리원');
INSERT INTO organizations (code, name) VALUES ('B552845', '한국농수산식품유통공사');
INSERT INTO organizations (code, name) VALUES ('1262000', '외교부');
INSERT INTO organizations (code, name) VALUES ('3030000', '서울특별시 성동구');
INSERT INTO organizations (code, name) VALUES ('B551457', '한국철도공사');
INSERT INTO organizations (code, name) VALUES ('9750000', '헌법재판소');
INSERT INTO organizations (code, name) VALUES ('3070000', '서울특별시 성북구');
INSERT INTO organizations (code, name) VALUES ('B552772', '보험개발원');
INSERT INTO organizations (code, name) VALUES ('B552518', '한국환경산업기술원');
INSERT INTO organizations (code, name) VALUES ('B551463', '한국문화예술교육진흥원');
INSERT INTO organizations (code, name) VALUES ('1471057', '식품의약품안전처 식품의약품안전평가원');
INSERT INTO organizations (code, name) VALUES ('B554626', '한국형사법무정책연구원');
INSERT INTO organizations (code, name) VALUES ('9760000', '중앙선거관리위원회');
INSERT INTO organizations (code, name) VALUES ('4201000', '강원특별자치도 강릉시');
INSERT INTO organizations (code, name) VALUES ('B340014', '한국대학교육협의회');
INSERT INTO organizations (code, name) VALUES ('B553530', '한국에너지공단');
INSERT INTO organizations (code, name) VALUES ('B553508', '국립낙동강생물자원관');
INSERT INTO organizations (code, name) VALUES ('B010003', '한국자산관리공사');
INSERT INTO organizations (code, name) VALUES ('5020000', '경상북도 포항시');
INSERT INTO organizations (code, name) VALUES ('4671000', '전북특별자치도 군산시');
INSERT INTO organizations (code, name) VALUES ('1360000', '기상청');
INSERT INTO organizations (code, name) VALUES ('1160100', '금융위원회');
INSERT INTO organizations (code, name) VALUES ('1342000', '교육부');
INSERT INTO organizations (code, name) VALUES ('1371033', '문화체육관광부 국립현대미술관');
INSERT INTO organizations (code, name) VALUES ('B551186', '한국과학기술정보연구원');
INSERT INTO organizations (code, name) VALUES ('B551210', '한국가스공사');
INSERT INTO organizations (code, name) VALUES ('4520000', '충청남도 아산시');
INSERT INTO organizations (code, name) VALUES ('6520000', '제주특별자치도 서귀포시');
INSERT INTO organizations (code, name) VALUES ('7150687', '부산광역시교육청 부산광역시교육청교육연구정보원');
INSERT INTO organizations (code, name) VALUES ('4810000', '전라남도 여수시');
INSERT INTO organizations (code, name) VALUES ('B555072', '한국산업기술기획평가원');
INSERT INTO organizations (code, name) VALUES ('B552867', '예술경영지원센터');
INSERT INTO organizations (code, name) VALUES ('B551504', '인천항만공사');
INSERT INTO organizations (code, name) VALUES ('B554388', '한국부동산원');
INSERT INTO organizations (code, name) VALUES ('1220000', '관세청');
INSERT INTO organizations (code, name) VALUES ('B554584', '의료기관평가인증원');
INSERT INTO organizations (code, name) VALUES ('B552644', '한국콘텐츠진흥원');
INSERT INTO organizations (code, name) VALUES ('B554805', '대구교통공사');
INSERT INTO organizations (code, name) VALUES ('B552551', '정보통신산업진흥원');
INSERT INTO organizations (code, name) VALUES ('B554393', '한국지능정보사회진흥원');
INSERT INTO organizations (code, name) VALUES ('B553664', '한국승강기안전공단');
INSERT INTO organizations (code, name) VALUES ('1250000', '통일부');
INSERT INTO organizations (code, name) VALUES ('5310000', '경상남도 진주시');
INSERT INTO organizations (code, name) VALUES ('B553748', '한국식품안전관리인증원');
INSERT INTO organizations (code, name) VALUES ('B551922', '부산도시공사');
INSERT INTO organizations (code, name) VALUES ('B551893', '한국남동발전㈜');
INSERT INTO organizations (code, name) VALUES ('B553774', '서울시설공단');
INSERT INTO organizations (code, name) VALUES ('1342068', '교육부 국사편찬위원회');
INSERT INTO organizations (code, name) VALUES ('1230000', '조달청');
INSERT INTO organizations (code, name) VALUES ('B551408', '한국주택금융공사');
INSERT INTO organizations (code, name) VALUES ('1834112', '우주항공청 우주환경센터');
INSERT INTO organizations (code, name) VALUES ('3660000', '대전광역시 서구');
INSERT INTO organizations (code, name) VALUES ('3110000', '서울특별시 은평구');
INSERT INTO organizations (code, name) VALUES ('3830000', '경기도 안양시');
INSERT INTO organizations (code, name) VALUES ('B500004', '한국도로공사');
INSERT INTO organizations (code, name) VALUES ('B410004', '대한석탄공사');
INSERT INTO organizations (code, name) VALUES ('1240000', '통계청');
INSERT INTO organizations (code, name) VALUES ('B551172', '국립암센터');
INSERT INTO organizations (code, name) VALUES ('7010000', '서울특별시교육청');
INSERT INTO organizations (code, name) VALUES ('5590000', '경기도 양주시');
INSERT INTO organizations (code, name) VALUES ('1371036', '문화체육관광부 국립민속박물관');
INSERT INTO organizations (code, name) VALUES ('4231000', '강원특별자치도 속초시');
INSERT INTO organizations (code, name) VALUES ('B553881', '한국교통안전공단');
INSERT INTO organizations (code, name) VALUES ('B554808', '대구공공시설관리공단');
INSERT INTO organizations (code, name) VALUES ('4050000', '경기도 용인시');
INSERT INTO organizations (code, name) VALUES ('B554009', '중소벤처기업진흥공단');
INSERT INTO organizations (code, name) VALUES ('B552729', '한국방송통신전파진흥원');
INSERT INTO organizations (code, name) VALUES ('B190021', '중소기업은행');
INSERT INTO organizations (code, name) VALUES ('B553912', '(주)에스알');
INSERT INTO organizations (code, name) VALUES ('B552735', '창업진흥원');
INSERT INTO organizations (code, name) VALUES ('B552520', '한국남부발전(주)');
INSERT INTO organizations (code, name) VALUES ('5110000', '경상북도 상주시');
INSERT INTO organizations (code, name) VALUES ('4070000', '경기도 이천시');
INSERT INTO organizations (code, name) VALUES ('B090041', '한국천문연구원');
INSERT INTO organizations (code, name) VALUES ('B553662', '한국등산트레킹지원센터');
INSERT INTO organizations (code, name) VALUES ('3630000', '광주광역시 광산구');
INSERT INTO organizations (code, name) VALUES ('B551184', '한국에너지기술연구원');
INSERT INTO organizations (code, name) VALUES ('B552555', '한국토지주택공사');
INSERT INTO organizations (code, name) VALUES ('B553961', '재단법인천안시복지재단');
INSERT INTO organizations (code, name) VALUES ('1360496', '기상청 항공기상청');
INSERT INTO organizations (code, name) VALUES ('B552625', '부산환경공단');
INSERT INTO organizations (code, name) VALUES ('B552640', '공무원연금공단');
INSERT INTO organizations (code, name) VALUES ('B552950', '서울특별시농수산식품공사');
INSERT INTO organizations (code, name) VALUES ('B553062', '게임물관리위원회');
INSERT INTO organizations (code, name) VALUES ('B553694', '기술보증기금');
INSERT INTO organizations (code, name) VALUES ('1450190', '산업통상자원부 국가기술표준원');
INSERT INTO organizations (code, name) VALUES ('3900000', '경기도 광명시');
INSERT INTO organizations (code, name) VALUES ('5050000', '경상북도 경주시');
INSERT INTO organizations (code, name) VALUES ('4510000', '충청남도 보령시');
INSERT INTO organizations (code, name) VALUES ('B555234', '한국도로교통공단');
INSERT INTO organizations (code, name) VALUES ('1421000', '중소벤처기업부');
INSERT INTO organizations (code, name) VALUES ('B552104', '중소기업기술정보진흥원');
INSERT INTO organizations (code, name) VALUES ('B260004', '한국국제교류재단');
INSERT INTO organizations (code, name) VALUES ('6290000', '광주광역시');
INSERT INTO organizations (code, name) VALUES ('4181000', '강원특별자치도 춘천시');
INSERT INTO organizations (code, name) VALUES ('4400000', '충청북도 제천시');
INSERT INTO organizations (code, name) VALUES ('4211000', '강원특별자치도 동해시');
INSERT INTO organizations (code, name) VALUES ('5430000', '경상남도 남해군');
INSERT INTO organizations (code, name) VALUES ('B554038', '한국수산자원공단');
INSERT INTO organizations (code, name) VALUES ('4060000', '경기도 파주시');
INSERT INTO organizations (code, name) VALUES ('3780000', '경기도 성남시');
INSERT INTO organizations (code, name) VALUES ('4420000', '충청북도 보은군');
INSERT INTO organizations (code, name) VALUES ('5690000', '세종특별자치시');
INSERT INTO organizations (code, name) VALUES ('3140000', '서울특별시 양천구');
INSERT INTO organizations (code, name) VALUES ('B554076', '(재)세종테크노파크');
INSERT INTO organizations (code, name) VALUES ('B553069', '재단법인충북테크노파크');
INSERT INTO organizations (code, name) VALUES ('B554922', '재단법인울산문화관광재단');
INSERT INTO organizations (code, name) VALUES ('B554597', '재단법인천안과학산업진흥원');
INSERT INTO organizations (code, name) VALUES ('5090000', '경상북도 영주시');
INSERT INTO organizations (code, name) VALUES ('4390000', '충청북도 충주시');
INSERT INTO organizations (code, name) VALUES ('3990000', '경기도 남양주시');
INSERT INTO organizations (code, name) VALUES ('3420000', '대구광역시 동구');
INSERT INTO organizations (code, name) VALUES ('3430000', '대구광역시 서구');
INSERT INTO organizations (code, name) VALUES ('4721000', '전북특별자치도 완주군');
INSERT INTO organizations (code, name) VALUES ('1833119', '국가유산청 국립해양유산연구소');
INSERT INTO organizations (code, name) VALUES ('5350000', '경상남도 김해시');
INSERT INTO organizations (code, name) VALUES ('4890000', '전라남도 보성군');
INSERT INTO organizations (code, name) VALUES ('6480000', '경상남도');
INSERT INTO organizations (code, name) VALUES ('4140000', '경기도 연천군');
INSERT INTO organizations (code, name) VALUES ('1371661', '문화체육관광부 국립국악고등학교');
INSERT INTO organizations (code, name) VALUES ('3670000', '대전광역시 유성구');
INSERT INTO organizations (code, name) VALUES ('3470000', '대구광역시 달서구');
INSERT INTO organizations (code, name) VALUES ('4170000', '경기도 양평군');
INSERT INTO organizations (code, name) VALUES ('5710000', '충청북도 청주시');
INSERT INTO organizations (code, name) VALUES ('4860000', '전라남도 곡성군');
INSERT INTO organizations (code, name) VALUES ('5600000', '경기도 포천시');
INSERT INTO organizations (code, name) VALUES ('B553554', '인천관광공사');
INSERT INTO organizations (code, name) VALUES ('3450000', '대구광역시 북구');
INSERT INTO organizations (code, name) VALUES ('5010000', '전라남도 신안군');
INSERT INTO organizations (code, name) VALUES ('5100000', '경상북도 영천시');
INSERT INTO organizations (code, name) VALUES ('3980000', '경기도 구리시');
INSERT INTO organizations (code, name) VALUES ('3050000', '서울특별시 동대문구');
INSERT INTO organizations (code, name) VALUES ('B554305', '재단법인전라남도관광재단');
INSERT INTO organizations (code, name) VALUES ('6510000', '제주특별자치도 제주시');
INSERT INTO organizations (code, name) VALUES ('3020000', '서울특별시 용산구');
INSERT INTO organizations (code, name) VALUES ('B553299', '재단법인강원정보문화진흥원');
INSERT INTO organizations (code, name) VALUES ('B551001', '독립기념관');
INSERT INTO organizations (code, name) VALUES ('4090000', '경기도 김포시');
INSERT INTO organizations (code, name) VALUES ('4490000', '충청남도 천안시');
INSERT INTO organizations (code, name) VALUES ('B552980', '수원시정연구원');
INSERT INTO organizations (code, name) VALUES ('3640000', '대전광역시 동구');
INSERT INTO organizations (code, name) VALUES ('4030000', '경기도 의왕시');
INSERT INTO organizations (code, name) VALUES ('4191000', '강원특별자치도 원주시');
INSERT INTO organizations (code, name) VALUES ('3700000', '울산광역시 남구');
INSERT INTO organizations (code, name) VALUES ('5440000', '경상남도 하동군');
INSERT INTO organizations (code, name) VALUES ('3730000', '울산광역시 울주군');
INSERT INTO organizations (code, name) VALUES ('4600000', '충청남도 홍성군');
INSERT INTO organizations (code, name) VALUES ('B553917', '주식회사공영홈쇼핑');
INSERT INTO organizations (code, name) VALUES ('4580000', '충청남도 서천군');
INSERT INTO organizations (code, name) VALUES ('1570100', '방송통신위원회');
INSERT INTO organizations (code, name) VALUES ('B551024', '국제방송교류재단');
INSERT INTO organizations (code, name) VALUES ('4610000', '충청남도 예산군');
INSERT INTO organizations (code, name) VALUES ('3190000', '서울특별시 동작구');
INSERT INTO organizations (code, name) VALUES ('B552062', '화성도시공사');
INSERT INTO organizations (code, name) VALUES ('B552546', '한국저작권위원회');
INSERT INTO organizations (code, name) VALUES ('B552679', '축산물품질평가원');
INSERT INTO organizations (code, name) VALUES ('B553701', '서민금융진흥원');
INSERT INTO organizations (code, name) VALUES ('B190030', '한국산업은행');
INSERT INTO organizations (code, name) VALUES ('B551505', '한국인터넷진흥원');
INSERT INTO organizations (code, name) VALUES ('B552149', '한국농어촌공사');
INSERT INTO organizations (code, name) VALUES ('1532000', '해양경찰청');
INSERT INTO organizations (code, name) VALUES ('B551365', '한국디자인진흥원');
INSERT INTO organizations (code, name) VALUES ('1790365', '개인정보보호위원회');
INSERT INTO organizations (code, name) VALUES ('1543309', '농림축산식품부 농식품공무원교육원');
INSERT INTO organizations (code, name) VALUES ('B553084', '국립생태원');
INSERT INTO organizations (code, name) VALUES ('6530000', '강원특별자치도');
INSERT INTO organizations (code, name) VALUES ('B555280', '주식회사한국중소벤처기업유통원');
INSERT INTO organizations (code, name) VALUES ('B554066', '시흥도시공사');
INSERT INTO organizations (code, name) VALUES ('B554958', '재외동포협력센터');
INSERT INTO organizations (code, name) VALUES ('B554031', '한아프리카재단');
INSERT INTO organizations (code, name) VALUES ('C100006', '서울대학교 연구소 차세대융합기술연구원');
INSERT INTO organizations (code, name) VALUES ('B555289', '국악방송');
INSERT INTO organizations (code, name) VALUES ('9720000', '국회 국회도서관');
INSERT INTO organizations (code, name) VALUES ('3480000', '대구광역시 달성군');
INSERT INTO organizations (code, name) VALUES ('3370000', '부산광역시 연제구');
INSERT INTO organizations (code, name) VALUES ('B554353', '재단법인경상남도관광재단');
INSERT INTO organizations (code, name) VALUES ('6430000', '충청북도');
INSERT INTO organizations (code, name) VALUES ('B553935', '서울관광재단');
INSERT INTO organizations (code, name) VALUES ('4840000', '전라남도 광양시');
INSERT INTO organizations (code, name) VALUES ('B552974', '부산관광공사');
INSERT INTO organizations (code, name) VALUES ('B010002', '통일연구원');
INSERT INTO organizations (code, name) VALUES ('B552917', '서울연구원');
INSERT INTO organizations (code, name) VALUES ('3590000', '광주광역시 동구');
INSERT INTO organizations (code, name) VALUES ('3040000', '서울특별시 광진구');
INSERT INTO organizations (code, name) VALUES ('1371829', '문화체육관광부 국립장애인도서관');
INSERT INTO organizations (code, name) VALUES ('B553357', '김해시도시개발공사');
INSERT INTO organizations (code, name) VALUES ('B551296', '인천광역시서구시설관리공단');
INSERT INTO organizations (code, name) VALUES ('5580000', '충청남도 계룡시');
INSERT INTO organizations (code, name) VALUES ('3210000', '서울특별시 서초구');
INSERT INTO organizations (code, name) VALUES ('5130000', '경상북도 경산시');
INSERT INTO organizations (code, name) VALUES ('B553482', '국립해양생물자원관');
INSERT INTO organizations (code, name) VALUES ('1833117', '국가유산청 국립무형유산원');
INSERT INTO organizations (code, name) VALUES ('B555316', '재단법인충청북도역사문화연구원');
INSERT INTO organizations (code, name) VALUES ('B553826', '한국특허전략개발원');
INSERT INTO organizations (code, name) VALUES ('B552481', '한국예탁결제원');
INSERT INTO organizations (code, name) VALUES ('B551939', '제주특별자치도개발공사');
INSERT INTO organizations (code, name) VALUES ('1192266', '해양수산부 국립수산과학원');
INSERT INTO organizations (code, name) VALUES ('B550624', '한국산업단지공단');
INSERT INTO organizations (code, name) VALUES ('B550936', '한국과학기술기획평가원(KISTEP)');
INSERT INTO organizations (code, name) VALUES ('4460000', '충청북도 괴산군');
INSERT INTO organizations (code, name) VALUES ('1400377', '산림청 국립산림과학원');
INSERT INTO organizations (code, name) VALUES ('B552521', '한국중부발전(주)');
INSERT INTO organizations (code, name) VALUES ('5380000', '경상남도 양산시');
INSERT INTO organizations (code, name) VALUES ('B552486', '한국소방산업기술원');
INSERT INTO organizations (code, name) VALUES ('B552745', '한국사회적기업진흥원');
INSERT INTO organizations (code, name) VALUES ('1210000', '국세청');
INSERT INTO organizations (code, name) VALUES ('B551202', '한국보훈복지의료공단');
INSERT INTO organizations (code, name) VALUES ('B552719', '그랜드코리아레저(주)');
INSERT INTO organizations (code, name) VALUES ('4850000', '전라남도 담양군');
INSERT INTO organizations (code, name) VALUES ('B553501', '한국국토정보공사');
INSERT INTO organizations (code, name) VALUES ('3400000', '부산광역시 기장군');
INSERT INTO organizations (code, name) VALUES ('B552701', '제주관광공사');
INSERT INTO organizations (code, name) VALUES ('B552570', '태권도진흥재단');
INSERT INTO organizations (code, name) VALUES ('B554618', '중소벤처기업연구원');
INSERT INTO organizations (code, name) VALUES ('1480802', '환경부 화학물질안전원');
INSERT INTO organizations (code, name) VALUES ('3330000', '부산광역시 해운대구');
INSERT INTO organizations (code, name) VALUES ('B551174', '한국보건산업진흥원');
INSERT INTO organizations (code, name) VALUES ('B551378', '수도권매립지관리공사');
INSERT INTO organizations (code, name) VALUES ('1690000', '방위사업청');
INSERT INTO organizations (code, name) VALUES ('3380000', '부산광역시 수영구');
INSERT INTO organizations (code, name) VALUES ('3360000', '부산광역시 강서구');
INSERT INTO organizations (code, name) VALUES ('B554639', '한국환경연구원');
INSERT INTO organizations (code, name) VALUES ('1371063', '문화체육관광부 한국예술종합학교');
INSERT INTO organizations (code, name) VALUES ('1721115', '과학기술정보통신부 국립중앙과학관');
INSERT INTO organizations (code, name) VALUES ('B553931', '해양환경공단');
INSERT INTO organizations (code, name) VALUES ('B552986', '세종학당재단');
INSERT INTO organizations (code, name) VALUES ('1371577', '문화체육관광부 국립한글박물관');
INSERT INTO organizations (code, name) VALUES ('B190033', '한국은행');
INSERT INTO organizations (code, name) VALUES ('B551938', '울산항만공사');
INSERT INTO organizations (code, name) VALUES ('B551458', '한국학중앙연구원');
INSERT INTO organizations (code, name) VALUES ('B552536', '한국산업기술진흥원');
INSERT INTO organizations (code, name) VALUES ('B552474', '한국노인인력개발원');
INSERT INTO organizations (code, name) VALUES ('1613436', '국토교통부 국토지리정보원');
INSERT INTO organizations (code, name) VALUES ('4830000', '전라남도 나주시');
INSERT INTO organizations (code, name) VALUES ('B552782', '여수광양항만공사');
INSERT INTO organizations (code, name) VALUES ('B550928', '국민건강보험공단');
INSERT INTO organizations (code, name) VALUES ('B554625', '한국직업능력연구원');
INSERT INTO organizations (code, name) VALUES ('1543319', '농림축산식품부 국립종자원');
INSERT INTO organizations (code, name) VALUES ('B551897', '서울특별시성동구도시관리공단');
INSERT INTO organizations (code, name) VALUES ('B554334', '국가철도공단');
INSERT INTO organizations (code, name) VALUES ('4771000', '전북특별자치도 순창군');
INSERT INTO organizations (code, name) VALUES ('B350011', '한국기계연구원');
INSERT INTO organizations (code, name) VALUES ('B551553', '한국식품연구원');
INSERT INTO organizations (code, name) VALUES ('B553699', '(재)한국저작권보호원');
INSERT INTO organizations (code, name) VALUES ('1371025', '문화체육관광부 대한민국예술원');
INSERT INTO organizations (code, name) VALUES ('5250000', '경상북도 울진군');
INSERT INTO organizations (code, name) VALUES ('B552881', '국가평생교육진흥원');
INSERT INTO organizations (code, name) VALUES ('B190016', '신용보증기금');
INSERT INTO organizations (code, name) VALUES ('B554729', '한국농업기술진흥원');
INSERT INTO organizations (code, name) VALUES ('1192464', '해양수산부 국립해양측위정보원');
INSERT INTO organizations (code, name) VALUES ('B550935', '광주과학기술원');
INSERT INTO organizations (code, name) VALUES ('1833113', '국가유산청 국립고궁박물관');
INSERT INTO organizations (code, name) VALUES ('B551541', '경제인문사회연구회');
INSERT INTO organizations (code, name) VALUES ('B552711', '건설근로자공제회');
INSERT INTO organizations (code, name) VALUES ('B553077', '소상공인시장진흥공단');
INSERT INTO organizations (code, name) VALUES ('B552657', '국립중앙의료원');
INSERT INTO organizations (code, name) VALUES ('1760000', '인사혁신처');
INSERT INTO organizations (code, name) VALUES ('5670000', '경상남도 창원시');
INSERT INTO organizations (code, name) VALUES ('1741050', '행정안전부 국가기록원');

-- Initial data for common_code table
-- SR Category
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_CATEGORY', 'OPEN_API', 'OPEN API', 1, true, 'OPEN API 관련', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_CATEGORY', 'INDIVIDUAL_PORTAL', '개별포털', 2, true, '개별포털 관련', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_CATEGORY', 'OTHER', '기타', 3, true, '기타', NOW(), NOW());

-- SR Request Type
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'DATA_REQ', '자료요청', 1, true, '자료 요청', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'TECH_SUPPORT', '기술지원', 2, true, '기술 지원', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'REMOTE_REQ', '원격요청', 3, true, '원격 지원 요청', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'FIREWALL', '방화벽설정', 4, true, '방화벽 설정 요청', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'FUNC_ERROR', '기능오류', 5, true, '기능 오류 신고', NOW(), NOW());
INSERT INTO common_code (code_group, code_value, code_name, sort_order, is_active, description, created_at, updated_at) VALUES ('SR_REQUEST_TYPE', 'OTHER', '기타', 6, true, '기타', NOW(), NOW());
