INSERT INTO organizations (code, name) VALUES ('1741000', '행정안전부');
INSERT INTO organizations (code, name) VALUES ('3000000', '서울특별시');
INSERT INTO organizations (code, name) VALUES ('3010000', '서울특별시 종로구');
INSERT INTO organizations (code, name) VALUES ('3020000', '서울특별시 중구');
INSERT INTO organizations (code, name) VALUES ('3030000', '서울특별시 용산구');
INSERT INTO organizations (code, name) VALUES ('3040000', '서울특별시 성동구');
INSERT INTO organizations (code, name) VALUES ('3050000', '서울특별시 광진구');
INSERT INTO organizations (code, name) VALUES ('3060000', '서울특별시 동대문구');
INSERT INTO organizations (code, name) VALUES ('3070000', '서울특별시 중랑구');
INSERT INTO organizations (code, name) VALUES ('3080000', '서울특별시 성북구');
INSERT INTO organizations (code, name) VALUES ('3090000', '서울특별시 강북구');
INSERT INTO organizations (code, name) VALUES ('3100000', '서울특별시 도봉구');
INSERT INTO organizations (code, name) VALUES ('3110000', '서울특별시 노원구');
INSERT INTO organizations (code, name) VALUES ('3120000', '서울특별시 은평구');
INSERT INTO organizations (code, name) VALUES ('3130000', '서울특별시 서대문구');
INSERT INTO organizations (code, name) VALUES ('3140000', '서울특별시 마포구');
INSERT INTO organizations (code, name) VALUES ('3150000', '서울특별시 양천구');
INSERT INTO organizations (code, name) VALUES ('3160000', '서울특별시 강서구');
INSERT INTO organizations (code, name) VALUES ('3170000', '서울특별시 구로구');
INSERT INTO organizations (code, name) VALUES ('3180000', '서울특별시 금천구');
INSERT INTO organizations (code, name) VALUES ('3190000', '서울특별시 영등포구');
INSERT INTO organizations (code, name) VALUES ('3200000', '서울특별시 동작구');
INSERT INTO organizations (code, name) VALUES ('3210000', '서울특별시 관악구');
INSERT INTO organizations (code, name) VALUES ('3220000', '서울특별시 서초구');
INSERT INTO organizations (code, name) VALUES ('3230000', '서울특별시 강남구');
INSERT INTO organizations (code, name) VALUES ('3240000', '서울특별시 송파구');
INSERT INTO organizations (code, name) VALUES ('3250000', '서울특별시 강동구');
INSERT INTO organizations (code, name) VALUES ('6110000', '부산광역시');
INSERT INTO organizations (code, name) VALUES ('6270000', '대구광역시');
INSERT INTO organizations (code, name) VALUES ('6280000', '인천광역시');
INSERT INTO organizations (code, name) VALUES ('6290000', '광주광역시');
INSERT INTO organizations (code, name) VALUES ('6300000', '대전광역시');
INSERT INTO organizations (code, name) VALUES ('6310000', '울산광역시');
INSERT INTO organizations (code, name) VALUES ('6410000', '경기도');
INSERT INTO organizations (code, name) VALUES ('6420000', '강원도');
INSERT INTO organizations (code, name) VALUES ('6430000', '충청북도');
INSERT INTO organizations (code, name) VALUES ('6440000', '충청남도');
INSERT INTO organizations (code, name) VALUES ('6450000', '전라북도');
INSERT INTO organizations (code, name) VALUES ('6460000', '전라남도');
INSERT INTO organizations (code, name) VALUES ('6470000', '경상북도');
INSERT INTO organizations (code, name) VALUES ('6480000', '경상남도');
INSERT INTO organizations (code, name) VALUES ('6500000', '제주특별자치도');
